import type { BoardState, CanvasElement } from '../types/whiteboard';

export interface BoardTemplate {
  id: string;
  name: string;
  description: string;
  category: string;
  icon: string;
  elements: CanvasElement[];
}

export const INITIAL_WELCOME_BOARD: BoardState = {
  metadata: {
    id: 'default-board',
    title: 'My Miro Whiteboard',
    lastModified: Date.now(),
    version: 1,
  },
  viewport: {
    x: 100,
    y: 80,
    zoom: 1,
  },
  elements: [
    // Welcome Header Card (Rectangle)
    {
      id: 'welcome-card',
      type: 'rectangle',
      x: 120,
      y: 40,
      width: 540,
      height: 110,
      fill: '#1e293b',
      stroke: '#3b82f6',
      strokeWidth: 2,
      strokeStyle: 'solid',
      borderRadius: 16,
      text: '✨ Welcome to Miro Whiteboard!\nDrag, zoom, draw, sticky notes, shapes & real-time tools.',
      fontSize: 18,
      fontColor: '#ffffff',
      textAlign: 'center',
      zIndex: 1,
    },
    // Sticky Notes Showcase
    {
      id: 'sticky-1',
      type: 'sticky',
      x: 120,
      y: 190,
      width: 200,
      height: 180,
      colorTheme: 'yellow',
      text: '💡 Brainstorming\n• Idea 1: Infinite canvas\n• Idea 2: Clean Miro UI\n• Idea 3: Smooth undo/redo',
      fontSize: 14,
      textAlign: 'left',
      zIndex: 2,
    },
    {
      id: 'sticky-2',
      type: 'sticky',
      x: 360,
      y: 190,
      width: 200,
      height: 180,
      colorTheme: 'coral',
      text: '🎯 Goals for Sprint\n1. Connect UI shapes\n2. Freehand sketching\n3. Export to PNG/JSON',
      fontSize: 14,
      textAlign: 'left',
      zIndex: 3,
    },
    {
      id: 'sticky-3',
      type: 'sticky',
      x: 600,
      y: 190,
      width: 200,
      height: 180,
      colorTheme: 'green',
      text: '🚀 Pro-tips\n• Press Space+Drag to Pan\n• Scroll wheel to Zoom\n• Double-click to edit text\n• Shift+Click multi-select',
      fontSize: 14,
      textAlign: 'left',
      zIndex: 4,
    },
    // Flowchart preview
    {
      id: 'shape-start',
      type: 'circle',
      x: 140,
      y: 430,
      width: 140,
      height: 140,
      fill: '#ecfdf5',
      stroke: '#10b981',
      strokeWidth: 3,
      strokeStyle: 'solid',
      text: 'Start',
      fontSize: 18,
      fontColor: '#065f46',
      textAlign: 'center',
      zIndex: 5,
    },
    {
      id: 'arrow-1',
      type: 'arrow',
      x: 280,
      y: 500,
      width: 120,
      height: 40,
      startX: 280,
      startY: 500,
      endX: 410,
      endY: 500,
      stroke: '#64748b',
      strokeWidth: 3,
      strokeStyle: 'solid',
      arrowHead: 'end',
      zIndex: 6,
    },
    {
      id: 'shape-process',
      type: 'rectangle',
      x: 410,
      y: 450,
      width: 180,
      height: 100,
      fill: '#eff6ff',
      stroke: '#3b82f6',
      strokeWidth: 3,
      strokeStyle: 'solid',
      borderRadius: 12,
      text: 'Design & Build',
      fontSize: 16,
      fontColor: '#1e40af',
      textAlign: 'center',
      zIndex: 7,
    },
    {
      id: 'arrow-2',
      type: 'arrow',
      x: 590,
      y: 500,
      width: 120,
      height: 40,
      startX: 590,
      startY: 500,
      endX: 720,
      endY: 500,
      stroke: '#64748b',
      strokeWidth: 3,
      strokeStyle: 'solid',
      arrowHead: 'end',
      zIndex: 8,
    },
    {
      id: 'shape-end',
      type: 'rectangle',
      x: 720,
      y: 450,
      width: 160,
      height: 100,
      fill: '#fdf4ff',
      stroke: '#a855f7',
      strokeWidth: 3,
      strokeStyle: 'solid',
      borderRadius: 24,
      text: 'Ship Product 🚀',
      fontSize: 16,
      fontColor: '#7e22ce',
      textAlign: 'center',
      zIndex: 9,
    },
    // Standalone Text
    {
      id: 'text-intro',
      type: 'text',
      x: 140,
      y: 620,
      width: 500,
      height: 40,
      text: 'Select any item above to see the floating contextual tool dock!',
      fontSize: 16,
      fontColor: '#64748b',
      fontWeight: '600',
      textAlign: 'left',
      zIndex: 10,
    },
  ],
};

export const TEMPLATES: BoardTemplate[] = [
  {
    id: 'kanban',
    name: 'Kanban Sprint Board',
    description: 'Track workflow with To Do, In Progress, Review, and Done columns.',
    category: 'Agile & Workflow',
    icon: 'Columns3',
    elements: [
      {
        id: 'col-todo',
        type: 'rectangle',
        x: 100,
        y: 100,
        width: 260,
        height: 520,
        fill: '#f8fafc',
        stroke: '#cbd5e1',
        strokeWidth: 2,
        strokeStyle: 'solid',
        borderRadius: 14,
        text: '📋 TO DO',
        fontSize: 16,
        fontColor: '#334155',
        textAlign: 'center',
        zIndex: 1,
      },
      {
        id: 'col-in-progress',
        type: 'rectangle',
        x: 390,
        y: 100,
        width: 260,
        height: 520,
        fill: '#eff6ff',
        stroke: '#93c5fd',
        strokeWidth: 2,
        strokeStyle: 'solid',
        borderRadius: 14,
        text: '⚡ IN PROGRESS',
        fontSize: 16,
        fontColor: '#1d4ed8',
        textAlign: 'center',
        zIndex: 2,
      },
      {
        id: 'col-review',
        type: 'rectangle',
        x: 680,
        y: 100,
        width: 260,
        height: 520,
        fill: '#fefce8',
        stroke: '#fde047',
        strokeWidth: 2,
        strokeStyle: 'solid',
        borderRadius: 14,
        text: '🔍 CODE REVIEW',
        fontSize: 16,
        fontColor: '#a16207',
        textAlign: 'center',
        zIndex: 3,
      },
      {
        id: 'col-done',
        type: 'rectangle',
        x: 970,
        y: 100,
        width: 260,
        height: 520,
        fill: '#f0fdf4',
        stroke: '#86efac',
        strokeWidth: 2,
        strokeStyle: 'solid',
        borderRadius: 14,
        text: '✅ DONE',
        fontSize: 16,
        fontColor: '#15803d',
        textAlign: 'center',
        zIndex: 4,
      },
      {
        id: 'task-1',
        type: 'sticky',
        x: 120,
        y: 170,
        width: 220,
        height: 120,
        colorTheme: 'yellow',
        text: 'User onboarding tour & tooltips',
        fontSize: 14,
        textAlign: 'left',
        zIndex: 5,
      },
      {
        id: 'task-2',
        type: 'sticky',
        x: 120,
        y: 310,
        width: 220,
        height: 120,
        colorTheme: 'blue',
        text: 'Dark mode theme toggle',
        fontSize: 14,
        textAlign: 'left',
        zIndex: 6,
      },
      {
        id: 'task-3',
        type: 'sticky',
        x: 410,
        y: 170,
        width: 220,
        height: 120,
        colorTheme: 'coral',
        text: 'Canvas gesture optimizations',
        fontSize: 14,
        textAlign: 'left',
        zIndex: 7,
      },
      {
        id: 'task-4',
        type: 'sticky',
        x: 700,
        y: 170,
        width: 220,
        height: 120,
        colorTheme: 'purple',
        text: 'Export board high-res PNG',
        fontSize: 14,
        textAlign: 'left',
        zIndex: 8,
      },
      {
        id: 'task-5',
        type: 'sticky',
        x: 990,
        y: 170,
        width: 220,
        height: 120,
        colorTheme: 'green',
        text: 'Infinite grid background math',
        fontSize: 14,
        textAlign: 'left',
        zIndex: 9,
      },
    ],
  },
  {
    id: 'brainstorming',
    name: 'Brainstorming & Mind Map',
    description: 'Central concept with interconnected ideas and sticky notes.',
    category: 'Ideation',
    icon: 'Lightbulb',
    elements: [
      {
        id: 'center-idea',
        type: 'circle',
        x: 460,
        y: 280,
        width: 200,
        height: 200,
        fill: '#6366f1',
        stroke: '#4338ca',
        strokeWidth: 4,
        strokeStyle: 'solid',
        text: 'Next Gen\nProduct Vision',
        fontSize: 18,
        fontColor: '#ffffff',
        textAlign: 'center',
        zIndex: 1,
      },
      {
        id: 'node-top',
        type: 'sticky',
        x: 460,
        y: 50,
        width: 200,
        height: 150,
        colorTheme: 'yellow',
        text: '⚡ Performance\n• 60fps canvas\n• WebGL acceleration\n• Instant sync',
        fontSize: 14,
        textAlign: 'left',
        zIndex: 2,
      },
      {
        id: 'node-left',
        type: 'sticky',
        x: 140,
        y: 290,
        width: 200,
        height: 150,
        colorTheme: 'coral',
        text: '🎨 Design\n• Minimalist toolbar\n• Tactile sticky notes\n• Smooth arrows',
        fontSize: 14,
        textAlign: 'left',
        zIndex: 3,
      },
      {
        id: 'node-right',
        type: 'sticky',
        x: 780,
        y: 290,
        width: 200,
        height: 150,
        colorTheme: 'blue',
        text: '🤝 Collaboration\n• Live cursors\n• Audio rooms\n• Threaded comments',
        fontSize: 14,
        textAlign: 'left',
        zIndex: 4,
      },
      {
        id: 'node-bottom',
        type: 'sticky',
        x: 460,
        y: 550,
        width: 200,
        height: 150,
        colorTheme: 'green',
        text: '🔌 Integrations\n• GitHub / Jira\n• Slack webhook\n• Figma sync',
        fontSize: 14,
        textAlign: 'left',
        zIndex: 5,
      },
      {
        id: 'arr-top',
        type: 'arrow',
        x: 560,
        y: 200,
        width: 10,
        height: 80,
        startX: 560,
        startY: 280,
        endX: 560,
        endY: 200,
        stroke: '#818cf8',
        strokeWidth: 3,
        strokeStyle: 'solid',
        arrowHead: 'end',
        zIndex: 6,
      },
      {
        id: 'arr-left',
        type: 'arrow',
        x: 340,
        y: 365,
        width: 120,
        height: 10,
        startX: 460,
        startY: 380,
        endX: 340,
        endY: 380,
        stroke: '#818cf8',
        strokeWidth: 3,
        strokeStyle: 'solid',
        arrowHead: 'end',
        zIndex: 7,
      },
      {
        id: 'arr-right',
        type: 'arrow',
        x: 660,
        y: 380,
        width: 120,
        height: 10,
        startX: 660,
        startY: 380,
        endX: 780,
        endY: 380,
        stroke: '#818cf8',
        strokeWidth: 3,
        strokeStyle: 'solid',
        arrowHead: 'end',
        zIndex: 8,
      },
      {
        id: 'arr-bottom',
        type: 'arrow',
        x: 560,
        y: 480,
        width: 10,
        height: 70,
        startX: 560,
        startY: 480,
        endX: 560,
        endY: 550,
        stroke: '#818cf8',
        strokeWidth: 3,
        strokeStyle: 'solid',
        arrowHead: 'end',
        zIndex: 9,
      },
    ],
  },
  {
    id: 'retro',
    name: 'Team Retrospective (Mad / Sad / Glad)',
    description: 'Feedback columns for agile sprint retrospectives.',
    category: 'Team Meetings',
    icon: 'MessageSquarePlus',
    elements: [
      {
        id: 'col-glad',
        type: 'rectangle',
        x: 100,
        y: 100,
        width: 320,
        height: 540,
        fill: '#f0fdf4',
        stroke: '#22c55e',
        strokeWidth: 2,
        strokeStyle: 'solid',
        borderRadius: 14,
        text: '💚 GLAD (What went well)',
        fontSize: 16,
        fontColor: '#166534',
        textAlign: 'center',
        zIndex: 1,
      },
      {
        id: 'col-sad',
        type: 'rectangle',
        x: 460,
        y: 100,
        width: 320,
        height: 540,
        fill: '#fef2f2',
        stroke: '#ef4444',
        strokeWidth: 2,
        strokeStyle: 'solid',
        borderRadius: 14,
        text: '💔 SAD (What could be improved)',
        fontSize: 16,
        fontColor: '#991b1b',
        textAlign: 'center',
        zIndex: 2,
      },
      {
        id: 'col-ideas',
        type: 'rectangle',
        x: 820,
        y: 100,
        width: 320,
        height: 540,
        fill: '#eff6ff',
        stroke: '#3b82f6',
        strokeWidth: 2,
        strokeStyle: 'solid',
        borderRadius: 14,
        text: '🚀 ACTION ITEMS & IDEAS',
        fontSize: 16,
        fontColor: '#1e40af',
        textAlign: 'center',
        zIndex: 3,
      },
      {
        id: 'retro-1',
        type: 'sticky',
        x: 120,
        y: 170,
        width: 280,
        height: 120,
        colorTheme: 'green',
        text: 'Great team communication during the crunch time!',
        fontSize: 14,
        textAlign: 'left',
        zIndex: 4,
      },
      {
        id: 'retro-2',
        type: 'sticky',
        x: 480,
        y: 170,
        width: 280,
        height: 120,
        colorTheme: 'coral',
        text: 'CI pipeline was flaky on Friday afternoons.',
        fontSize: 14,
        textAlign: 'left',
        zIndex: 5,
      },
      {
        id: 'retro-3',
        type: 'sticky',
        x: 840,
        y: 170,
        width: 280,
        height: 120,
        colorTheme: 'blue',
        text: 'Automate weekly regression test suite.',
        fontSize: 14,
        textAlign: 'left',
        zIndex: 6,
      },
    ],
  },
];
