import type { BoardState, CanvasElement } from '../types/whiteboard';

export interface BoardTemplate {
  id: string;
  name: string;
  description: string;
  category: string;
  icon: string;
  elements: CanvasElement[];
}

export const INITIAL_WELCOME_BOARD: BoardState = {
  metadata: {
    id: 'default-board',
    title: 'Ziro Product Roadmap',
    lastModified: Date.now(),
    version: 1,
    isStarred: true,
  },
  viewport: {
    x: 60,
    y: 50,
    zoom: 0.95,
  },
  elements: [
    // Miro Frame Container
    {
      id: 'frame-welcome',
      type: 'frame',
      x: 80,
      y: 30,
      width: 860,
      height: 620,
      title: '✨ Welcome to Ziro Whiteboard',
      fill: 'rgba(255, 255, 255, 0.75)',
      stroke: '#cbd5e1',
      zIndex: 0,
    },
    // Header Banner
    {
      id: 'welcome-card',
      type: 'rectangle',
      x: 110,
      y: 70,
      width: 800,
      height: 80,
      fill: '#050038', // Miro dark navy
      stroke: '#4262ff',
      strokeWidth: 2,
      strokeStyle: 'solid',
      borderRadius: 12,
      text: '⚡ Ziro — The Modern Collaborative Infinite Whiteboard\nDraw, connect ideas with sticky notes, flowchart shapes, and live cursors in real-time.',
      fontSize: 15,
      fontColor: '#ffffff',
      textAlign: 'center',
      zIndex: 1,
    },
    // Miro Sticky Notes Row
    {
      id: 'sticky-1',
      type: 'sticky',
      x: 110,
      y: 180,
      width: 190,
      height: 170,
      colorTheme: 'yellow',
      text: '💡 Brainstorming\n• Infinite 60fps canvas\n• Real-time live cursors\n• 8 Ziro pastel themes',
      fontSize: 13,
      textAlign: 'left',
      zIndex: 2,
    },
    {
      id: 'sticky-2',
      type: 'sticky',
      x: 320,
      y: 180,
      width: 190,
      height: 170,
      colorTheme: 'pink',
      text: '🎯 Sprint Goals\n1. Multi-board workspace\n2. Live cross-tab sync\n3. High-res vector PNG export',
      fontSize: 13,
      textAlign: 'left',
      zIndex: 3,
    },
    {
      id: 'sticky-3',
      type: 'sticky',
      x: 530,
      y: 180,
      width: 190,
      height: 170,
      colorTheme: 'blue',
      text: '🚀 Pro-Tips\n• Space+Drag to Pan\n• Scroll wheel to Zoom\n• Double-click to edit text',
      fontSize: 13,
      textAlign: 'left',
      zIndex: 4,
    },
    {
      id: 'sticky-4',
      type: 'sticky',
      x: 740,
      y: 180,
      width: 170,
      height: 170,
      colorTheme: 'green',
      text: '🤝 Collaboration\nClick "Collab Simulation" or open in 2 tabs to see live cursors!',
      fontSize: 13,
      textAlign: 'left',
      zIndex: 5,
    },
    // Flowchart Diagram
    {
      id: 'shape-start',
      type: 'circle',
      x: 130,
      y: 390,
      width: 130,
      height: 130,
      fill: '#d5f5e3',
      stroke: '#10b981',
      strokeWidth: 2.5,
      strokeStyle: 'solid',
      text: 'Idea / Problem',
      fontSize: 14,
      fontColor: '#065f46',
      textAlign: 'center',
      zIndex: 6,
    },
    {
      id: 'arrow-1',
      type: 'arrow',
      x: 260,
      y: 455,
      width: 110,
      height: 20,
      startX: 260,
      startY: 455,
      endX: 380,
      endY: 455,
      stroke: '#4262ff',
      strokeWidth: 3,
      strokeStyle: 'solid',
      arrowHead: 'end',
      zIndex: 7,
    },
    {
      id: 'shape-process',
      type: 'rectangle',
      x: 380,
      y: 405,
      width: 180,
      height: 100,
      fill: '#d0e7ff',
      stroke: '#4262ff',
      strokeWidth: 2.5,
      strokeStyle: 'solid',
      borderRadius: 12,
      text: 'Design in Ziro',
      fontSize: 15,
      fontColor: '#1e40af',
      textAlign: 'center',
      zIndex: 8,
    },
    {
      id: 'arrow-2',
      type: 'arrow',
      x: 560,
      y: 455,
      width: 110,
      height: 20,
      startX: 560,
      startY: 455,
      endX: 680,
      endY: 455,
      stroke: '#4262ff',
      strokeWidth: 3,
      strokeStyle: 'solid',
      arrowHead: 'end',
      zIndex: 9,
    },
    {
      id: 'shape-end',
      type: 'rectangle',
      x: 680,
      y: 405,
      width: 190,
      height: 100,
      fill: '#e6d9ff',
      stroke: '#8b5cf6',
      strokeWidth: 2.5,
      strokeStyle: 'solid',
      borderRadius: 24,
      text: 'Ship to Production 🚀',
      fontSize: 15,
      fontColor: '#581c87',
      textAlign: 'center',
      zIndex: 10,
    },
    // Standalone Text
    {
      id: 'text-footer',
      type: 'text',
      x: 130,
      y: 560,
      width: 600,
      height: 40,
      text: '✨ Click any shape or note to customize colors, styles, or add text.',
      fontSize: 14,
      fontColor: '#64748b',
      fontWeight: '600',
      textAlign: 'left',
      zIndex: 11,
    },
  ],
};

export const TEMPLATES: BoardTemplate[] = [
  {
    id: 'kanban',
    name: 'Kanban Sprint Board',
    description: 'Agile workflow with To Do, In Progress, Review, and Done columns.',
    category: 'Agile & Workflow',
    icon: 'Columns3',
    elements: [
      {
        id: 'frame-kanban',
        type: 'frame',
        x: 60,
        y: 60,
        width: 1220,
        height: 590,
        title: '⚡ Sprint Kanban Board',
        fill: 'rgba(255, 255, 255, 0.75)',
        stroke: '#cbd5e1',
        zIndex: 0,
      },
      {
        id: 'col-todo',
        type: 'rectangle',
        x: 90,
        y: 100,
        width: 260,
        height: 520,
        fill: '#f8fafc',
        stroke: '#cbd5e1',
        strokeWidth: 2,
        strokeStyle: 'solid',
        borderRadius: 14,
        text: '📋 TO DO',
        fontSize: 15,
        fontColor: '#334155',
        textAlign: 'center',
        zIndex: 1,
      },
      {
        id: 'col-in-progress',
        type: 'rectangle',
        x: 380,
        y: 100,
        width: 260,
        height: 520,
        fill: '#eff6ff',
        stroke: '#93c5fd',
        strokeWidth: 2,
        strokeStyle: 'solid',
        borderRadius: 14,
        text: '⚡ IN PROGRESS',
        fontSize: 15,
        fontColor: '#1d4ed8',
        textAlign: 'center',
        zIndex: 2,
      },
      {
        id: 'col-review',
        type: 'rectangle',
        x: 670,
        y: 100,
        width: 260,
        height: 520,
        fill: '#fefce8',
        stroke: '#fde047',
        strokeWidth: 2,
        strokeStyle: 'solid',
        borderRadius: 14,
        text: '🔍 CODE REVIEW',
        fontSize: 15,
        fontColor: '#a16207',
        textAlign: 'center',
        zIndex: 3,
      },
      {
        id: 'col-done',
        type: 'rectangle',
        x: 960,
        y: 100,
        width: 260,
        height: 520,
        fill: '#f0fdf4',
        stroke: '#86efac',
        strokeWidth: 2,
        strokeStyle: 'solid',
        borderRadius: 14,
        text: '✅ DONE',
        fontSize: 15,
        fontColor: '#15803d',
        textAlign: 'center',
        zIndex: 4,
      },
      {
        id: 'task-1',
        type: 'sticky',
        x: 110,
        y: 170,
        width: 220,
        height: 120,
        colorTheme: 'yellow',
        text: 'User onboarding & Ziro tooltips',
        fontSize: 13,
        textAlign: 'left',
        zIndex: 5,
      },
      {
        id: 'task-2',
        type: 'sticky',
        x: 110,
        y: 310,
        width: 220,
        height: 120,
        colorTheme: 'blue',
        text: 'Dark mode theme toggle',
        fontSize: 13,
        textAlign: 'left',
        zIndex: 6,
      },
      {
        id: 'task-3',
        type: 'sticky',
        x: 400,
        y: 170,
        width: 220,
        height: 120,
        colorTheme: 'pink',
        text: 'Cross-tab live collaboration sync',
        fontSize: 13,
        textAlign: 'left',
        zIndex: 7,
      },
      {
        id: 'task-4',
        type: 'sticky',
        x: 690,
        y: 170,
        width: 220,
        height: 120,
        colorTheme: 'purple',
        text: 'Export board high-res PNG',
        fontSize: 13,
        textAlign: 'left',
        zIndex: 8,
      },
      {
        id: 'task-5',
        type: 'sticky',
        x: 980,
        y: 170,
        width: 220,
        height: 120,
        colorTheme: 'green',
        text: 'Infinite grid background math',
        fontSize: 13,
        textAlign: 'left',
        zIndex: 9,
      },
    ],
  },
  {
    id: 'brainstorming',
    name: 'Brainstorming & Mind Map',
    description: 'Central concept with interconnected ideas and sticky notes.',
    category: 'Ideation',
    icon: 'Lightbulb',
    elements: [
      {
        id: 'frame-mindmap',
        type: 'frame',
        x: 80,
        y: 30,
        width: 960,
        height: 720,
        title: '💡 Ideation & Concept Map',
        fill: 'rgba(255, 255, 255, 0.75)',
        stroke: '#cbd5e1',
        zIndex: 0,
      },
      {
        id: 'center-idea',
        type: 'circle',
        x: 460,
        y: 280,
        width: 200,
        height: 200,
        fill: '#4262ff',
        stroke: '#050038',
        strokeWidth: 3,
        strokeStyle: 'solid',
        text: 'Ziro Product\nVision 2026',
        fontSize: 17,
        fontColor: '#ffffff',
        textAlign: 'center',
        zIndex: 1,
      },
      {
        id: 'node-top',
        type: 'sticky',
        x: 460,
        y: 70,
        width: 200,
        height: 140,
        colorTheme: 'yellow',
        text: '⚡ Performance\n• 60fps canvas\n• WebGL acceleration',
        fontSize: 13,
        textAlign: 'left',
        zIndex: 2,
      },
      {
        id: 'node-left',
        type: 'sticky',
        x: 120,
        y: 300,
        width: 200,
        height: 140,
        colorTheme: 'pink',
        text: '🎨 Design\n• Ziro-identical toolbar\n• Smooth shapes & arrows',
        fontSize: 13,
        textAlign: 'left',
        zIndex: 3,
      },
      {
        id: 'node-right',
        type: 'sticky',
        x: 800,
        y: 300,
        width: 200,
        height: 140,
        colorTheme: 'blue',
        text: '🤝 Collaboration\n• Live cursors\n• Audio rooms',
        fontSize: 13,
        textAlign: 'left',
        zIndex: 4,
      },
      {
        id: 'node-bottom',
        type: 'sticky',
        x: 460,
        y: 550,
        width: 200,
        height: 140,
        colorTheme: 'green',
        text: '🔌 Integrations\n• GitHub / Jira\n• Slack webhook',
        fontSize: 13,
        textAlign: 'left',
        zIndex: 5,
      },
      {
        id: 'arr-top',
        type: 'arrow',
        x: 560,
        y: 210,
        width: 10,
        height: 70,
        startX: 560,
        startY: 280,
        endX: 560,
        endY: 210,
        stroke: '#4262ff',
        strokeWidth: 2.5,
        strokeStyle: 'solid',
        arrowHead: 'end',
        zIndex: 6,
      },
      {
        id: 'arr-left',
        type: 'arrow',
        x: 320,
        y: 370,
        width: 140,
        height: 10,
        startX: 460,
        startY: 370,
        endX: 320,
        endY: 370,
        stroke: '#4262ff',
        strokeWidth: 2.5,
        strokeStyle: 'solid',
        arrowHead: 'end',
        zIndex: 7,
      },
      {
        id: 'arr-right',
        type: 'arrow',
        x: 660,
        y: 370,
        width: 140,
        height: 10,
        startX: 660,
        startY: 370,
        endX: 800,
        endY: 370,
        stroke: '#4262ff',
        strokeWidth: 2.5,
        strokeStyle: 'solid',
        arrowHead: 'end',
        zIndex: 8,
      },
      {
        id: 'arr-bottom',
        type: 'arrow',
        x: 560,
        y: 480,
        width: 10,
        height: 70,
        startX: 560,
        startY: 480,
        endX: 560,
        endY: 550,
        stroke: '#4262ff',
        strokeWidth: 2.5,
        strokeStyle: 'solid',
        arrowHead: 'end',
        zIndex: 9,
      },
    ],
  },
  {
    id: 'retro',
    name: 'Sprint Retrospective',
    description: 'Mad, Sad, Glad columns for agile sprint reviews.',
    category: 'Team Meetings',
    icon: 'MessageSquarePlus',
    elements: [
      {
        id: 'frame-retro',
        type: 'frame',
        x: 60,
        y: 60,
        width: 1140,
        height: 600,
        title: '🎯 Team Retrospective (Mad / Sad / Glad)',
        fill: 'rgba(255, 255, 255, 0.75)',
        stroke: '#cbd5e1',
        zIndex: 0,
      },
      {
        id: 'col-glad',
        type: 'rectangle',
        x: 90,
        y: 100,
        width: 320,
        height: 530,
        fill: '#f0fdf4',
        stroke: '#22c55e',
        strokeWidth: 2,
        strokeStyle: 'solid',
        borderRadius: 14,
        text: '💚 GLAD (What went well)',
        fontSize: 15,
        fontColor: '#166534',
        textAlign: 'center',
        zIndex: 1,
      },
      {
        id: 'col-sad',
        type: 'rectangle',
        x: 450,
        y: 100,
        width: 320,
        height: 530,
        fill: '#fef2f2',
        stroke: '#ef4444',
        strokeWidth: 2,
        strokeStyle: 'solid',
        borderRadius: 14,
        text: '💔 SAD (What could be improved)',
        fontSize: 15,
        fontColor: '#991b1b',
        textAlign: 'center',
        zIndex: 2,
      },
      {
        id: 'col-ideas',
        type: 'rectangle',
        x: 810,
        y: 100,
        width: 320,
        height: 530,
        fill: '#eff6ff',
        stroke: '#4262ff',
        strokeWidth: 2,
        strokeStyle: 'solid',
        borderRadius: 14,
        text: '🚀 ACTION ITEMS & IDEAS',
        fontSize: 15,
        fontColor: '#1e40af',
        textAlign: 'center',
        zIndex: 3,
      },
      {
        id: 'retro-1',
        type: 'sticky',
        x: 110,
        y: 170,
        width: 280,
        height: 120,
        colorTheme: 'green',
        text: 'Great team collaboration during sprint!',
        fontSize: 13,
        textAlign: 'left',
        zIndex: 4,
      },
      {
        id: 'retro-2',
        type: 'sticky',
        x: 470,
        y: 170,
        width: 280,
        height: 120,
        colorTheme: 'pink',
        text: 'Need clearer specifications for complex UI widgets.',
        fontSize: 13,
        textAlign: 'left',
        zIndex: 5,
      },
      {
        id: 'retro-3',
        type: 'sticky',
        x: 830,
        y: 170,
        width: 280,
        height: 120,
        colorTheme: 'blue',
        text: 'Automate weekly release testing.',
        fontSize: 13,
        textAlign: 'left',
        zIndex: 6,
      },
    ],
  },
];
